### PR TITLE
OCPBUGS-28597: Disable PO

### PR DESCRIPTION
**Pull request by kevinrizza**
Temporarily disable this component while upgrading rukpak with a breaking change

### CODE REVIEW

**Comment by grokspawn** [comment]
re-title commit in the form "UPSTREAM: <drop>:" ?

**Review by grokspawn — APPROVED** [review]

**Comment by kuiwang02** [comment]
wait @jianzhangbjz to add qe-approved

**Comment by ncdc** [comment]
Seeing if a comment will kick tide

**Pull request merged**
